services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: recipes
    ports:
      - "5432:5432"
  app:
    build:
      context: .
      dockerfile: Dockerfile
#   environment:
#      - DB_HOST=db
#      - DB_PORT=3306
#      - DB_USER=root
#      - DB_PASSWORD=6672
#      - DB_NAME=recipes
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
  migrate: # used once to migrate from sqlite db to postgres db
    image: python:3.9
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "pip install -r requirements.txt && python migrate_data.py"
