services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: recipes
    ports:
      - "3306:3306"
  app:
    build:
      context: .
      dockerfile: Dockerfile
#   environment:
#      - DB_HOST=db
#      - DB_PORT=3306
#      - DB_USER=root
#      - DB_PASSWORD=6672
#      - DB_NAME=recipes
    env_file: 
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
  migrate: # used to migrate from sqlite db to mysql db
    image: python:3.9
    volumes:
      - .:/app
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "pip install -r requirements.txt && python migrate_data.py"
